[core]
	engine = pg
	plan_file = sqitch.plan
	top_dir = .

[engine "pg"]
	registry = sqitch
	client = psql

[target "local"]
	uri = db:pg://depopdba@local/postgres

[target "dev"]
	uri = db:pg://depopdba@dev/postgres

[target "staging"]
	uri = db:pg://depopdba@service-user-default-dispute-workflow.cnrpoumyfd1x.us-east-1.rds.amazonaws.com/postgres

[target "production"]
	uri = db:pg://depopdba@service-user-default-dispute-workflow-12-6.ckh7hwnufggc.us-east-1.rds.amazonaws.com/postgres
