pullRequests.grouping = [{"name":"patches","title":"Scala Steward Patch updates","filter":[{"version":"patch"}]},{"name":"minor","title":"Scala Steward Minor updates","filter":[{"version":"minor"}]}]

