# Copy the pre-built jar file into a prebuilt base image:
FROM 594471699039.dkr.ecr.us-east-1.amazonaws.com/mirror/amazoncorretto:17
ARG SOURCE_JAR
COPY ${SOURCE_JAR} ./executable.jar

ENTRYPOINT exec env java ${JAVA_OPTS} -jar executable.jar
