spring:
  output:
    ansi:
      enabled: ALWAYS
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  deployment-resource-pattern: classpath*:com/depop/cx/drc/workflow/*.bpmn
