environment: production
accountName: services-production
accountTag: prod-svcs
service_domain: user
service_group: default
service_name: dispute
service_role: workflow
dns_override_fqdn: disputes.depop.systems

loadbalancer:
  port: 9000
  alb:
    access_log_bucket: us-east-1-prod-svcs-elb-access-logs
    certificate: arn:aws:acm:us-east-1:093904767316:certificate/2552a016-50f6-4f43-8a22-ca5dabdbb68b,arn:aws:acm:us-east-1:093904767316:certificate/d0c46172-5267-4cb0-8baa-062357fc532f
    enabled: true

resources:
  limits:
    memory: 5Gi
  requests:
    memory: 3Gi
    cpu: 150m

secrets:
  ENV_DB_PASSWORD: production/services/user/default/dispute/workflow/_default/postgres_app_password
  ENV_OKTA_CLIENT_ID: production/services/user/default/dispute/workflow/_default/okta_client_id
  ENV_OKTA_CLIENT_SECRET: production/services/user/default/dispute/workflow/_default/okta_client_secret
  ENV_DEPOP_CLIENT_ID: production/services/user/default/dispute/workflow/_default/depop_client_id
  ENV_DEPOP_CLIENT_SECRET: production/services/user/default/dispute/workflow/_default/depop_client_secret
  ENV_SHIPPING_API_SECRET: production/services/user/default/dispute/workflow/_default/shipping_api_secret
  ENV_API_USERNAME: production/services/user/default/dispute/workflow/_default/api_username
  ENV_API_PASSWORD: production/services/user/default/dispute/workflow/_default/api_password
serviceConfig:
  JAVA_OPTS: -Dpolyglot.engine.WarnInterpreterOnly=false
  SPRING_PROFILES_ACTIVE: production_deployment
  ENV_DB_URL: jdbc:postgresql://service-user-default-dispute-workflow-12-6.ckh7hwnufggc.us-east-1.rds.amazonaws.com/disputeworkflow?autosave=conservative
  ENV_DB_USER: disputeworkflow_app
  ENV_OKTA_CLIENT_ISSUER_URI: https://depop.okta.com
  ENV_OKTA_CLIENT_REDIRECT_URI: https://disputes.depop.systems
  ENV_OAUTH2_RESOURCE_SERVER_JWK_SET_URI: https://security-default-clientauth-api.eks-default.prod-app.dpop.co.uk/.well-known/jwks.json
  ENV_OAUTH2_RESOURCE_SERVER_ISSUER_URI: depop-oauth-introspection
  ENV_DEPOP_CLIENT_TOKEN_URL: https://security-default-clientauth-api.eks-default.prod-app.dpop.co.uk/oauth2/access_token/
  CHECKOUT_HOST: https://checkout-default-checkout-server.eks-default.prod-app.dpop.co.uk
  DRC_HOST: https://user-default-dispute-internal.eks-default.prod-app.dpop.co.uk
  PAYMENTS_HOST: https://payments-default-payments-api.eks-default.prod-app.dpop.co.uk/
  SHIPPING_HOST: https://fulfilment-default-shipping-internal.eks-default.prod-app.dpop.co.uk
  USER_HOST: https://django-default-django-api.eks-default.prod-app.dpop.co.uk

chart:
  name: generic-service
  version: ^2

autoscaling:
  maxReplicas: 12
  minReplicas: 4

datadogTracing:
  agent:
    enabled: false
