---
envname: stage
accountTag: stage-svcs
service_domain: user
service_group: default
service_name: dispute
service_role: workflow
iamRoleARN: arn:aws:iam::183284569534:role/service-user-default-dispute-workflow
image:
  repository: 594471699039.dkr.ecr.us-east-1.amazonaws.com/user-default/dispute-workflow
loadbalancer:
  access_log_bucket: us-east-1-stage-svcs-elb-access-logs
  securitygroups: sg-050dfecc994a32014
  certificate: arn:aws:acm:us-east-1:183284569534:certificate/c352c7cd-9b12-43a0-8227-3670f0367bec
resources:
  limits:
    memory: 1G
  requests:
    memory: 800M
    cpu: 200m
serviceConfig:
  JAVA_OPTS: "-Dlogger.file=/etc/service-config/logback.xml"
  SPRING_PROFILE: stage_deployment
chart:
  name: scala-service
  version: "~1.10.0"