---
envname: stage
accountTag: stage-svcs
service_domain: user
service_group: default
service_name: dispute
service_role: workflow
iamRoleARN: arn:aws:iam::183284569534:role/service-user-default-dispute-workflow
image:
  repository: 594471699039.dkr.ecr.us-east-1.amazonaws.com/user-default/dispute-workflow
loadbalancer:
  access_log_bucket: us-east-1-stage-svcs-elb-access-logs
  securitygroups: sg-050dfecc994a32014
  certificate: arn:aws:acm:us-east-1:183284569534:certificate/c352c7cd-9b12-43a0-8227-3670f0367bec
resources:
  limits:
    memory: 4G
  requests:
    memory: 4G
    cpu: 2
secrets:
  ENV_DB_PASSWORD: staging/services/user/default/dispute/workflow/_default/postgres_app_password
  ENV_OKTA_CLIENT_ID: staging/services/user/default/dispute/workflow/_default/okta_client_id
  ENV_OKTA_CLIENT_SECRET: staging/services/user/default/dispute/workflow/_default/okta_client_secret
serviceConfig:
  JAVA_OPTS: "-Dpolyglot.engine.WarnInterpreterOnly=false"
  SPRING_PROFILES_ACTIVE: stage_deployment
  ENV_DB_URL: jdbc:postgresql://service-user-default-dispute-workflow.cnrpoumyfd1x.us-east-1.rds.amazonaws.com/disputeworkflow
  ENV_DB_USER: disputeworkflow_app
  ENV_OKTA_CLIENT_ISSUER_URI: https://depop.okta.com
  ENV_OKTA_CLIENT_REDIRECT_URI: https://user-default-dispute-workflow.stage-svcs.dpop.co.uk
  ENV_OAUTH2_RESOURCE_SERVER_JWK_SET_URI: https://security-default-clientauth-api.stage-app.dpop.co.uk/.well-known/jwks.json
  ENV_OAUTH2_RESOURCE_SERVER_ISSUER_URI: depop-oauth-introspection
autoscaling:
  cpu: 65
  memory: 75
  minReplicas: 3
  maxReplicas: 4
cluster: staging
chart:
  name: scala-service
  version: "~1.10.0"