service_domain: user
service_group: default
service_name: dispute
service_role: workflow
accountName: services-staging
accountTag: stage-svcs
environment: staging
serviceTier: critical
serviceOwner: cx

defaults:
  pagerduty:
    enabled: false

customMonitors:
  - name: Delegate execution latency is too high
    query: avg(last_5m):max:camunda.delegate.execution.95percentile{$DEFAULT_FILTERS} by {delegate_class_name} > 1000
    pagerduty:
      enabled: false
  - name: Delegate errors count is too high
    query: sum(last_5m):sum:camunda.delegate.failure{$DEFAULT_FILTERS} by {exception_class_name}.as_count().rollup(sum, 60) > 10
    pagerduty:
      enabled: false
    requireFullWindow: false

stdv1Monitors:
  enabled: false

chart:
  name: datadog
  version: ^1
