spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/depopdba"
    username: depopdba
    password: depopdba
