spring:
  output:
    ansi:
      enabled: ALWAYS
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
  deployment-resource-pattern: classpath*:**/drc-*.bpmn
