version: '3.5'
services:
  dispute-workflow-postgres-local:
    image: 594471699039.dkr.ecr.us-east-1.amazonaws.com/mirror/postgres:11.5
    container_name: dispute-workflow-postgres-local
    environment:
      - POSTGRES_USER=depopdba
      - POSTGRES_PASSWORD=depopdba
    ports:
      - "5432:5432"
