---
meta:
  name: "disputeworkflow"
  team: "platform"
  pipeline: ((grab meta.name))
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource
      tag: v0.21.0
  - name: slack-notification
    source:
      repository: cfcommunity/slack-notification-resource
    type: docker-image
resources:
  - name: code-repo
    type: pull-request
    check_every: 1m
    source:
      repository: depop/dispute-workflow
      access_token: ((dpdb-machine-repo-access-token))
      paths:
        - db/main/*/*
  - name: slack-alert
    source:
      url: ((concourse-slack-webhook-url))
    type: slack-notification
jobs:
  - name: env-test
    max_in_flight: 1
    plan:
      - get: code-repo
        trigger: true
      - task: dpdb-test
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: 594471699039.dkr.ecr.us-east-1.amazonaws.com/tools/dcind
          inputs:
            - name: code-repo
          run:
            path: /bin/test
        params:
          APPLICATION: disputeworkflow
          GITHUB_TOKEN: ((dpdb-machine-repo-access-token))
          GITHUB_REPO: depop/dispute-workflow
          target: staging
        on_success:
          put: set-env-test-success
          resource: code-repo
          params:
            comment: 'Database environment tests have been run'
            path: code-repo
            status: pending
          get_params: { skip_download: true }
        on_failure:
          put: set-env-test-failure
          resource: code-repo
          params:
            comment: 'Database environment tests failed'
            path: code-repo
            status: failure
          get_params: { skip_download: true }
  - name: deploy-staging
    max_in_flight: 1
    plan:
      - get: code-repo
        passed: [ env-test ]
      - task: dpdb-staging
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: 594471699039.dkr.ecr.us-east-1.amazonaws.com/tools/dcind
          inputs:
            - name: code-repo
          run:
            path: /bin/deploy
        params:
          APPLICATION: disputeworkflow
          GITHUB_TOKEN: ((dpdb-machine-repo-access-token))
          GITHUB_REPO: depop/dispute-workflow
          target: staging
        on_success:
          do:
            - put: set-staging-deployed
              resource: code-repo
              params:
                comment: 'Database changes deployed to staging'
                path: code-repo
                status: pending
              get_params: { skip_download: true }
            - put: slack-alert
              params:
                channel: '#dba'
                icon_emoji: ':concourseci:'
                text: 'disputeworkflow staging database deployed: <https://default-concourse.dflt-ops.dpop.co.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME | $BUILD_JOB_NAME #$BUILD_NAME>'
                username: ConcourseCI
        on_failure:
          do:
            - put: set-staging-failed
              resource: code-repo
              params:
                comment: 'Database changes failed to deploy to staging'
                path: code-repo
                status: failure
              get_params: { skip_download: true }
            - put: slack-alert
              params:
                channel: '#dba'
                icon_emoji: ':concourseci_red:'
                text: 'disputeworkflow staging database deployment failed: <https://default-concourse.dflt-ops.dpop.co.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME | $BUILD_JOB_NAME #$BUILD_NAME>'
                username: ConcourseCI
  - name: deploy-production
    max_in_flight: 1
    plan:
      - get: code-repo
        passed: [ deploy-staging ]
      - task: dpdb
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: 594471699039.dkr.ecr.us-east-1.amazonaws.com/tools/dcind
          inputs:
            - name: code-repo
          run:
            path: /bin/deploy
        params:
          APPLICATION: disputeworkflow
          GITHUB_TOKEN: ((dpdb-machine-repo-access-token))
          GITHUB_REPO: depop/dispute-workflow
          target: production
        on_success:
          do:
            - put: set-production-deployed
              resource: code-repo
              params:
                comment: 'Database changes deployed to production'
                path: code-repo
                status: success
              get_params: { skip_download: true }
            - put: slack-alert
              params:
                channel: '#dba'
                icon_emoji: ':concourseci:'
                text: 'disputeworkflow production database deployed: <https://default-concourse.dflt-ops.dpop.co.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME | $BUILD_JOB_NAME #$BUILD_NAME>'
                username: ConcourseCI
        on_failure:
          do:
            - put: set-production-failed
              resource: code-repo
              params:
                comment: 'Database changes failed to deploy to production'
                path: code-repo
                status: failure
              get_params: { skip_download: true }
            - put: slack-alert
              params:
                channel: '#dba'
                icon_emoji: ':concourseci_red:'
                text: 'disputeworkflow production database deployment failed: <https://default-concourse.dflt-ops.dpop.co.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME | $BUILD_JOB_NAME #$BUILD_NAME>'
                username: ConcourseCI
