# common
camunda:
  bpm:
    metrics:
      db-reporter-activate: true
      enabled: true

spring:
  jpa:
    properties:
      hibernate:
        generate_statistics: true

server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
      client:
        request:
          autotime:
            enabled: true
    enable:
      all: true

logging:
  level:
    io.micrometer.datadog: INFO
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: OFF
    com.depop.cx.drc.workflow.metrics.engine: INFO

---

# dev profile
spring:
  config:
    activate:
      on-profile: local
management:
  metrics:
    tags:
      service: "user-default-dispute-workflow"
      version: "deadbee"
      env: "local-local"
      env_type: "local"
      env_name: "local"
      service-domain: "user"
      service-group: "default"
      service-name: "dispute"
      service-role: "workflow"
      pod_name: "local"
      kube_namespace: "local"

---

#      datadog:
#        enabled: true
#        api-key: ${ENV_DATADOG_API_KEY}
#        application-key: ${ENV_DATADOG_APP_KEY}
#        step: 20s
#        connect-timeout: 1s
#        descriptions: true
#        read-timeout: 10s
#        uri: "https://pvtlink.process.datadoghq.com"

# stage profile
spring:
  config:
    activate:
      on-profile: stage
management:
  metrics:
    export:
      statsd:
        enabled: true
        host: ${METRICS_HOST}
        port: ${METRICS_PORT}
        flavor: datadog
    tags:
      service: ${SERVICE_DOMAIN}-${SERVICE_GROUP}-${SERVICE_NAME}-${SERVICE_ROLE}
      version: ${APP_VERSION}
      env: ${ENV_TYPE}-${ENV_NAME}
      env_type: ${ENV_TYPE}
      env_name: ${ENV_NAME}
      service-domain: ${SERVICE_DOMAIN}
      service-group: ${SERVICE_GROUP}
      service-name: ${SERVICE_NAME}
      service-role: ${SERVICE_ROLE}
      pod_name: ${POD_NAME}
      kube_namespace: ${POD_NAMESPACE}

---

# production profile
spring:
  config:
    activate:
      on-profile: production
management:
  metrics:
    export:
      statsd:
        enabled: true
        host: ${METRICS_HOST}
        port: ${METRICS_PORT}
        flavor: datadog
    tags:
      service: ${SERVICE_DOMAIN}-${SERVICE_GROUP}-${SERVICE_NAME}-${SERVICE_ROLE}
      version: ${APP_VERSION}
      env: ${ENV_TYPE}-${ENV_NAME}
      env_type: ${ENV_TYPE}
      env_name: ${ENV_NAME}
      service-domain: ${SERVICE_DOMAIN}
      service-group: ${SERVICE_GROUP}
      service-name: ${SERVICE_NAME}
      service-role: ${SERVICE_ROLE}
      pod_name: ${POD_NAME}
      kube_namespace: ${POD_NAMESPACE}