# common
server:
  port: 9000

spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: local-h2
    include: metrics, tracing, logging, camunda, security
    group:
      test: h2, local
      local-h2: h2, local
      local-postgres: postgres, local
      stage_deployment: postgres, stage
      production_deployment: postgres, production
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
      path-mapping:
        health: status
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

---

# local profile
spring:
  config:
    activate:
      on-profile: local

---

# stage profile
spring:
  config:
    activate:
      on-profile: stage

---

# production profile
spring:
  config:
    activate:
      on-profile: production
