# common
spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: dev-m2
    group:
      dev-m2: metrics,tracing,m2,dev
      dev-postgres: metrics,tracing,postgres,dev
      stage: metrics,tracing,postgres,stage

camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  deployment-resource-pattern: classpath*:com/depop/cx/drc/workflow/*.bpmn

#TODO: add opentelemetry trace fields
logging:
  register-shutdown-hook: true
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID: }){magenta} %clr(---){faint} %clr([%t]){faint} %clr([%X]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m %n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'

---

# dev profile
spring:
  config:
    activate:
      on-profile: dev

---

# stage profile
spring:
  config:
    activate:
      on-profile: stage

---

# production profile
spring:
  config:
    activate:
      on-profile: production



