# common
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: none
    generate-ddl: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/disputeworkflow"
    username: depopdba
    password: depopdba
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      idle-timeout: 600000
      leak-detection-threshold: 30000
      connection-timeout: 30000
      validation-timeout: 60000
      max-lifetime: 300000
      connection-init-sql: "SELECT 1"
      connection-test-query: "SELECT 1"

---

# local profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:postgresql://localhost:5432/disputeworkflow"
    username: disputeworkflow
    password: disputeworkflow

---

# stage profile
spring:
  config:
    activate:
      on-profile: stage
  datasource:
    url: ${ENV_DB_URL}
    username: ${ENV_DB_USER}
    password: ${ENV_DB_PASSWORD}

---

# production profile
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${ENV_DB_URL}
    username: ${ENV_DB_USER}
    password: ${ENV_DB_PASSWORD}