# common
spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: local-m2
    include: metrics, tracing, logging, camunda
    group:
      local-m2: m2, local
      local-postgres: postgres, local
      stage_deployment: postgres, stage

---

# local profile
spring:
  config:
    activate:
      on-profile: local

---

# stage profile
spring:
  config:
    activate:
      on-profile: stage

---

# production profile
spring:
  config:
    activate:
      on-profile: production



