# common
spring:
  jersey:
    application-path: /internal/v1

camunda:
  bpm:
    authorization:
      enabled: false
      tenant-check-enabled: false
    database:
      schema-update: false
    deployment-resource-pattern: classpath*:com/depop/cx/drc/workflow/*.bpmn
    default-serialization-format: application/json
    generic-properties:
      properties:
        history-cleanup-strategy: removalTimeBased
        history-removal-time-strategy: start

---

# h2 profile
spring:
  config:
    activate:
      on-profile: h2
camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    database:
      schema-update: true

---

# local profile
spring:
  config:
    activate:
      on-profile: local
camunda:
  bpm:
    generic-properties:
      properties:
        history-cleanup-enabled: true
        history-time-to-live: P30D
        history-cleanup-job-log-time-to-live: P7D
        history-cleanup-batch-window-start-time: "07:00"
        history-cleanup-batch-window-end-time: "20:00"

---

# stage profile
spring:
  config:
    activate:
      on-profile: stage
camunda:
  bpm:
    generic-properties:
      properties:
        history-cleanup-enabled: true
        history-time-to-live: P30D
        history-cleanup-job-log-time-to-live: P7D
        history-cleanup-batch-window-start-time: "07:00"
        history-cleanup-batch-window-end-time: "20:00"

---

# production profile
spring:
  config:
    activate:
      on-profile: production
camunda:
  bpm:
    generic-properties:
      properties:
        history-cleanup-enabled: true
        history-time-to-live: P180D
        history-cleanup-job-log-time-to-live: P7D
        history-cleanup-batch-window-start-time: "05:00"
        history-cleanup-batch-window-end-time: "11:00"
