# common
spring:
  jpa:
    properties:
      hibernate:
        generate_statistics: true

server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  metrics:
    export:
      datadog:
        enabled: false
        step: 30s
        uri: https://api.datadoghq.eu/
    tags:
      application: ${spring.application.name}
      env: ${spring.profiles}
    web:
      server:
        request:
          autotime:
            enabled: true
    enable:
      all: true

logging:
  level:
    io.micrometer.datadog: INFO
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: OFF
    com.depop.cx.drc.workflow.metrics.engine: INFO

---

#  metrics {
#    host = "localhost"
#    host = ${?METRICS_HOST}
#    port = 8125
#    port = ${?METRICS_PORT}
#    prefix = "depop.service.stdv1"
#    prefix = ${?METRICS_PREFIX}
#    service-domain = "user"
#    service-group  = "default"
#    service-name   = "namechange"
#    service-role   = "api"
#}

# dev profile
spring:
  config:
    activate:
      on-profile: local

---

# stage profile
spring:
  config:
    activate:
      on-profile: stage

---

# production profile
spring:
  config:
    activate:
      on-profile: production
