# common
spring:
  jersey:
    application-path: /internal/v1

camunda:
  bpm:
    authorization:
      enabled: false
      tenant-check-enabled: false
    database:
      schema-update: false
    deployment-resource-pattern: classpath*:com/depop/cx/drc/workflow/*.bpmn
    default-serialization-format: application/json
    generic-properties:
      properties:
        history-cleanup-enabled: true
        history-cleanup-metrics-enabled: false
        history-cleanup-strategy: removalTimeBased
        history-removal-time-strategy: start
        history-cleanup-job-log-time-to-live: P7D
    job-execution:
      enabled: true
    metrics:
      enabled: false

---

# h2 profile
spring:
  config:
    activate:
      on-profile: h2
camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    database:
      schema-update: true

---

# local profile
spring:
  config:
    activate:
      on-profile: local
camunda:
  bpm:
    generic-properties:
      properties:
        batch-operation-history-time-to-live: P1D
        history-time-to-live: P7D
        history-cleanup-job-log-time-to-live: P1D
        history-cleanup-batch-window-start-time: "00:00"
        history-cleanup-batch-window-end-time: "23:59"
        task-metrics-time-to-live: P1D

---

# stage profile
spring:
  config:
    activate:
      on-profile: stage
camunda:
  bpm:
    generic-properties:
      properties:
        batch-operation-history-time-to-live: P2D
        history-time-to-live: P30D
        history-cleanup-job-log-time-to-live: P2D
        history-cleanup-batch-window-start-time: "07:00"
        history-cleanup-batch-window-end-time: "20:00"
        task-metrics-time-to-live: P2D

---

# production profile
spring:
  config:
    activate:
      on-profile: production
camunda:
  bpm:
    generic-properties:
      properties:
        batch-operation-history-time-to-live: P7D
        history-time-to-live: P180D
        history-cleanup-job-log-time-to-live: P7D
        history-cleanup-batch-window-start-time: "04:00"
        history-cleanup-batch-window-end-time: "12:00"
        history-cleanup-degree-of-parallelism: 1
        history-cleanup-batch-size: 100
        task-metrics-time-to-live: P7D
