# common
opentracing:
  datadog:
    enabled: false
    trace:
      enabled: false
      health-metrics:
        enabled: true
      startup-logs: true
    writer-type: LoggingWriter
    logs-injection: true

logging:
  level:
    io:
      opentelemetry: DEBUG
---

# dev profile
spring:
  config:
    activate:
      on-profile: local
opentracing:
  datadog:
    enabled: true
    trace:
      enabled: true

---

# stage profile
spring:
  config:
    activate:
      on-profile: stage

---

# production profile
spring:
  config:
    activate:
      on-profile: production
