depop:
  drc:
    client:
      checkout-host: https://checkout-default-checkout-server.eks-default.stage-app.dpop.co.uk/
      drc-host: https://user-default-dispute-internal.eks-default.stage-app.dpop.co.uk/
      payments-host: https://payments-default-payments-api.eks-default.stage-app.dpop.co.uk/
      shipping-host: https://fulfilment-default-shipping-internal.eks-default.stage-app.dpop.co.uk/
      user-host: https://django-default-django-api.eks-default.stage-app.dpop.co.uk/
      comms-host: https://martech-default-comms-hub.eks-default.stage-svcs.dpop.co.uk
      picture-host: https://media-default-picture-api.eks-default.stage-app.dpop.co.uk
      product-host: https://django-default-django-api.eks-default.stage-app.dpop.co.uk
      blocking-host: https://blocking-default-blocking-internal.eks-default.stage-app.dpop.co.uk
      address-host: https://fulfilment-default-address-internal.eks-default.stage-app.dpop.co.uk
spring:
  security:
    oauth2:
      client:
        provider:
          depop:
            token-uri: https://security-default-clientauth-api.eks-default.stage-app.dpop.co.uk/oauth2/access_token/
        registration:
          depop:
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            provider: depop


---

# local profile
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        provider:
          depop:
            token-uri: https://security-default-clientauth-api.eks-default.stage-app.dpop.co.uk/oauth2/access_token/
---

# stage profile
spring:
  config:
    activate:
      on-profile: stage
  security:
    oauth2:
      client:
        provider:
          depop:
            token-uri: ${ENV_DEPOP_CLIENT_TOKEN_URL}
        registration:
          depop:
            client-id: ${ENV_DEPOP_CLIENT_ID}
            client-secret: ${ENV_DEPOP_CLIENT_SECRET}
depop:
  drc:
    client:
      checkout-host: ${CHECKOUT_HOST}
      drc-host: ${DRC_HOST}
      payments-host: ${PAYMENTS_HOST}
      shipping-host: ${SHIPPING_HOST}
      shipping-api-secret: ${ENV_SHIPPING_API_SECRET}
      user-host: ${USER_HOST}
      comms-host: ${COMMS_HOST}
      picture-host: ${PICTURE_HOST}
      product-host: ${PRODUCT_HOST}
      blocking-host: ${BLOCKING_HOST}
      address-host: ${ADDRESS_HOST}
---

# production profile
spring:
  config:
    activate:
      on-profile: production
  security:
    oauth2:
      client:
        provider:
          depop:
            token-uri: ${ENV_DEPOP_CLIENT_TOKEN_URL}
        registration:
          depop:
            client-id: ${ENV_DEPOP_CLIENT_ID}
            client-secret: ${ENV_DEPOP_CLIENT_SECRET}
depop:
  drc:
    client:
      checkout-host: ${CHECKOUT_HOST}
      drc-host: ${DRC_HOST}
      payments-host: ${PAYMENTS_HOST}
      shipping-host: ${SHIPPING_HOST}
      shipping-api-secret: ${ENV_SHIPPING_API_SECRET}
      user-host: ${USER_HOST}
      comms-host: ${COMMS_HOST}
      picture-host: ${PICTURE_HOST}
      product-host: ${PRODUCT_HOST}
      blocking-host: ${BLOCKING_HOST}
      address-host: ${ADDRESS_HOST}