[core]
	engine = pg
	plan_file = sqitch.plan
	top_dir = .

[engine "pg"]
	registry = sqitch
	client = psql

[target "local"]
	uri = db:pg://depopdba@local/disputeworkflow

[target "dev"]
	uri = db:pg://depopdba@dev/disputeworkflow

[target "staging"]
	uri = db:pg://depopdba@REPLACE_ME/disputeworkflow

[target "production"]
	uri = db:pg://depopdba@REPLACE_ME/disputeworkflow
