# ===============================================================
# THIS FILE IS MANAGED BY PLATFORM, EDITS WILL BE OVERWRITTEN
# CHANGES MUST BE MADE TO THE CENTRAL TEMPLATE HELD IN
# https://github.com/depop/repository-management
# ===============================================================

name: Run DPDB migration tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "master"
    paths:
      - "db/**"

jobs:
  dpdb-migration-tests:
    name: DPDB Migration Tests
    uses: depop/depop-workflows/.github/workflows/dpdb-migration-test.yml@master
    with:
      pgpass_targets: "staging,production"
